import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App Parallel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  other,
  slot,
}: Readonly<{
  children: React.ReactNode;
  other: React.ReactNode;
  slot: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col p-4 m-4 border border-black">
      <p>In this example, we have two parallel routes and a simple child page. All three get their proper loading states.</p>
      {other}
      {slot}
      {children}
    </div>
  );
}
